on:
  issues:
    types: [labeled, unlabeled]

jobs:
  assign_to_project:
    runs-on: ubuntu-latest
    name: Assign issue or PR to project based on label
    steps:
      - name: Assign to project
        uses: elastic/github-actions/project-assigner@2f6ec899e2b8481cc96ffe5f9104d121b6f6e418
        id: project_assigner
        with:
          issue-mappings: '[{"label": "wf_test", "projectNumber": 1, "columnName": "To do"}]'
          ghToken: ${{ secrets.PROJECT_ASSIGNER_TEST_TOKEN }}


